# Default values for helm.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1
image:
  repository: "vkletsko"
  tag: "v1.0.5-feb90a3"
  arch: ""
secret:
  name: "kbot"
  tokenKey: "token"
  tokenName: "TELE_TOKEN"
securityContext:
  privileged: true
