name: KBOT_CICD
on: push
jobs:
  ci:
    name: CI
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Run test
        run: make test
      - name: Login to ghcr.io
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ secrets.GHCR_USERNAME }}
          password: ${{ secrets.GHCR_TOKEN }}
      - name: Build and push
        env:
          APP: "kbot"
          REGISTRY: "ghcr.io"
          USERNAME: ${{ secrets.GHCR_USERNAME }}
        run: make image push
  
  cd:
    name: CD
    needs: ci
    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v3
        with:
          fetch-depth: 0    
      - run: echo "VERSION=$(git describe --tags --abbrev=0)-$(git rev-parse --short HEAD)" >> $GITHUB_ENV
      - run: echo "TARGETARCH=amd64" >> $GITHUB_ENV

      - uses: mikefarah/yq@master
        with:
          cmd: yq -i '.image.tag=strenv(VERSION) | .image.arch=strenv(TARGETARCH)' helm/values.yaml
      - name: Commit
        env:
          VERSION: ${{ env.VERSION }}
        run: | 
          git config user.name github-actions
          git config user.email github-actions@github.com
          git commit -am "update version $VERSION"
      - name: Push
        run: |
          git push
